In [1]:
import numpy as np

In [2]:
from time import process_time

In [7]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time-start_time)


0.015625


In [14]:
array = np.array([i for i in range(10000)])


start_time = process_time()

array += 5

end_time = process_time()


print(end_time-start_time)

0.0


### numpy arrays

In [18]:
#Creating a 1d array
a = np.array([1,2,3,4,5])
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

In [19]:
a.shape

(5,)

In [20]:
#Creating a 2D array
b = np.array([[1,2,3,4],[5,6,7,8,]])

b
b.shape

(2, 4)

In [21]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
c=np.array([[1,2,3,4],[5,6,7,8]], dtype=float)
c

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

### Initial Placeholders in Numpy Arrays

In [23]:
#Creating an array with initial values of 0

x = np.zeros((4,5))#Creating an array of zeros that have 4 rows and 5 colukns
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
#Creating a numpy array of ones
y = np.ones((3,3))
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
#Creattiing an array of a particular value
z = np.full((5,4),5)
z

#The code above creates an array with all elements containing a specific value. This is achieved using the .full() method.

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [27]:
#Creating an identity matrix using numpy array. Identity matrices have the same number of rows and columns.
i = np.eye(4)#WE only need to specify one value(sice number of rows and columns are the ame)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
#Creating an array with random values
r = np.random.random((3,4))
r
#All the values will be between zero and one.

array([[0.01892829, 0.70580243, 0.31482896, 0.14944125],
       [0.32655026, 0.69984195, 0.34792896, 0.82233281],
       [0.15009991, 0.99740451, 0.24124052, 0.68071264]])

In [34]:
#Creating an array with random integers within a specific range.
c = np.random.randint(10,100, (3,5))
c

# ... .randint(beginning_number, end_number, (rows, columns))

array([[11, 32, 31, 91, 15],
       [45, 60, 55, 15, 69],
       [88, 55, 18, 85, 23]])

In [36]:
#Creating an array of evenly spaced values... specifying the range and the number of values you want
d = np.linspace(10,30,5)
d

array([10., 15., 20., 25., 30.])

In [38]:
#Array of evenly spaced values, specifying the range and the step
e = np.arange(10,30,5)
e

array([10, 15, 20, 25])

In [41]:
#Converting a list to a numpy to an array
list2 = [10,20,20,20,50]

np_array2 = np.asarray(list2)
print(np_array2)
type(np_array2)

[10 20 20 20 50]


numpy.ndarray

### Analysing a numpy array

In [42]:
c = np.random.randint(10, 90, (5,5))
c

array([[11, 43, 14, 45, 62],
       [21, 72, 66, 55, 71],
       [26, 40, 67, 89, 70],
       [20, 88, 38, 82, 86],
       [71, 50, 20, 70, 14]])

In [45]:
#Array dimension
print(c.shape)

#number of dimensions
print(c.ndim)

#number of elements in an array
print(c.size)

#checking the datatype of values in the array
print(c.dtype)

(5, 5)
2
25
int32


### Mathematical operations on an np array


In [46]:
list4 = [1,2,3,4,5]
list5 = [6,7,8,9,10]

list4+list5
#When you use tha ddition operation between two lists it concatenates the two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [49]:
s = np.random.randint(0,10,(3,3))
t = np.random.randint(10,20,(3,3))

print(s)
print(t)



[[9 9 4]
 [3 8 0]
 [9 7 8]]
[[19 11 11]
 [14 10 19]
 [19 18 17]]


In [51]:
print(s+t)

print(s-t)

print(s/t)

print(s*t)

[[28 20 15]
 [17 18 19]
 [28 25 25]]
[[-10  -2  -7]
 [-11  -2 -19]
 [-10 -11  -9]]
[[0.47368421 0.81818182 0.36363636]
 [0.21428571 0.8        0.        ]
 [0.47368421 0.38888889 0.47058824]]
[[171  99  44]
 [ 42  80   0]
 [171 126 136]]


In [52]:

s = np.random.randint(0,10,(3,3))
t = np.random.randint(10,20,(3,3))

print(a)
print(b)
print(np.add(s,t))
print(np.subtract(s,t))
print(np.divide(s,t))
print(np.multiply(s,t))


[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]
[[22 13 25]
 [12 21 12]
 [15 21 21]]
[[-12 -13 -11]
 [ -8  -5 -10]
 [ -7 -15 -17]]
[[0.29411765 0.         0.38888889]
 [0.2        0.61538462 0.09090909]
 [0.36363636 0.16666667 0.10526316]]
[[ 85   0 126]
 [ 20 104  11]
 [ 44  54  38]]


### Array Manipulation

In [53]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)


[[8 5 1]
 [7 9 6]]
(2, 3)


In [55]:
#Transpose of an array
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[8 7]
 [5 9]
 [1 6]]
(3, 2)


In [56]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)


#Another way of finding transpose
trans2 = array.T
print(trans2, trans2.shape)

[[0 8 7]
 [8 1 5]]
(2, 3)
[[0 8]
 [8 1]
 [7 5]] (3, 2)


In [58]:
#Reshaping an array

a = np.random.randint(0, 10, (2,3))
print(a)
print(a.shape)

[[3 0 8]
 [3 0 4]]
(2, 3)


In [59]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[3 0]
 [8 3]
 [0 4]]
(3, 2)
